### PR TITLE
Fix issue #13

### PR DESCRIPTION
**Pull request by keiji**
USE_FINGERPRINT permission's protection level is not dangerous but normal.

### CODE REVIEW

**Comment by keiji** [comment]
@googlebot I signed it!

**Comment by thagikura** [comment]
Thanks for the pull request. 

Could you also delete the `FINGERPRINT_PERMISSION_REQUEST_CODE` constants which isn't used anymore? Otherwise the code looks fine.

**Comment by keiji** [comment]
@thagikura Thanks!

**Comment by thagikura** [comment]
Merged. googlebot says  unable to verify author consent, but I can see you consented in the previous comment.

Thanks for your contribution again!

**Comment by tjohns** [comment]
FYI: CLA manually verified.

Thanks!

**Pull request merged**
